name: Deploy Modern Book to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Docusaurus
        run: |
          npm install -g @docusaurus/init
          npx create-docusaurus@latest temp-book classic --yes
          cd temp-book
          npm install

      - name: Copy Content
        run: |
          cp -r ../README.md temp-book/docs/
          cp -r ../90-day-plan temp-book/docs/
          cp -r ../styles temp-book/static/
          
          # Create index page
          echo "# DeFi Learning Guide for Odoo Developers" > temp-book/docs/index.md
          echo "" >> temp-book/docs/index.md
          echo "Welcome to your comprehensive 90-day DeFi learning journey!" >> temp-book/docs/index.md
          echo "" >> temp-book/docs/index.md
          echo "[Start with Day 1](month-1/day-01)" >> temp-book/docs/index.md

      - name: Build Site
        run: |
          cd temp-book
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './temp-book/build'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 